version: "3"
services:
  app:
    build: ./app
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    ports:
      - "5000:5000"

  db:
    platform: linux/amd64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: 'mysql --user=root --password=password --execute "SHOW DATABASES;"'
      timeout: 5s
      retries: 2
